package com.example.gomokuee.Utils

import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

val MAIN_IMAGE_MIN_WIDTH = 300.dp
val MAIN_IMAGE_MIN_HEIGHT = 300.dp
val MAIN_IMAGE_MAX_WIDTH = 400.dp
val MAIN_IMAGE_MAX_HEIGHT = 400.dp
val MAIN_SCREEN_DEFAULT_PADDING = 10.dp
val MAIN_SCREEN_CONTAINER_PADDING = 40.dp
val MAIN_ROUNDED_CORNER_SHAPE = 20.dp

val HOME_FONT_SIZE = 12.sp

val HOME_USERNAME_FONT_SIZE = 30.sp

val CARD_PADDING = 30.dp
val DEFAULT_RADIUS = 5.dp
val CARD_ELEVATION = 4.dp
val BUTTON_NAME_SIZE = 12.sp
val SUBTITLE_FONT_SIZE = 15.sp
val BUTTON_RADIUS = 2.dp

val ROW_DEFAULT_PADDING = 20.dp

val ICON_SIZE = 30.dp

val BUTTON_DEFAULT_PADDING = 5.dp

val DEFAULT_CONTENT_PADDING = 10.dp
val TEXT_FIELD_NEW_GAME_PADDING = 15.dp

val AUTHOR_IMAGE_SIZE = 130.dp

val PASSWORD_SHOW_HIDE_ICON_SIZE = 20.dp

const val BOARD_PLUS_SYMBOL_ZERO_OFFSET = 0F

const val BOARD_PLUS_SYMBOL_HALF_OFFSET = 0.5F

const val BOARD_PLUS_SYMBOL_FULL_OFFSET = 1F

const val BOARD_PLUS_SYMBOL_STROKE_WIDTH = 60F

const val PLAY_SCREEN_BUTTON_MAX_WIDTH = 0.7F

const val PLAY_SCREEN_CONTAINER_MAX_WIDTH = 0.85F